name: Check

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        zeek_version:
          - zeek-lts
          - zeek

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: zeek/action-zkg-install@v2
      with:
        zeek_version: ${{ matrix.zeek_version }}
